application: clear-rock-814
version: test
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /static/(.*\.(webapp))$
  static_files: static/\1
  upload: static/.*\.(webapp)$
  http_headers:
    Content-Type: application/x-web-app-manifest+json
- url: /static/(.*\.(appcache))$
  static_files: static/\1
  upload: static/.*\.(appcache)$
  http_headers:
    Content-Type: text/cache-manifest
- url: /static
  static_dir: static
  http_headers:
    Access-Control-Allow-Origin: "*"
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: django
  version: "1.5"
- name: jinja2
  version: "latest"